name: screenshot_observer
description: screenshot callback
version: 0.0.1
homepage: https://github.com/supernovel/flutter_screenshot_observer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.supernovel.screenshot_observer
        pluginClass: ScreenshotObserverPlugin
      ios:
        pluginClass: ScreenshotObserverPlugin
